RMX3031:[RealmeParts]: Specify FLAG_IMMUTABLE flag to PendingIntent
Fixes:

java.lang.IllegalArgumentException: com.realmeparts: Targeting S+ (version 31 and above)
requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality
depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

Change-Id: I74cfb00b6801ff9600aa3586e310d10be31a32e3
Signed-off-by: Nishant Kumar <www.rajsonu13@gmail.com>